#!/usr/local/bin/bash

export P4PORT=${P4PORT:-rnd-scm.bmc.com:4742}
export P4USER=${P4USER:-pacander}
export P4CLIENT=${P4CLIENT:-packy_pacbook}
export P4TICKETS=${P4TICKETS:-$HOME/.p4tickets}

if [ -f $HOME/.bash_perforce_functions ]; then
    source $HOME/.bash_perforce_functions
fi

