#!/usr/bin/env bash
# for syntax highlightling in emacs, mostly

export GITDIR=$HOME/git
export CFGDIR=$GITDIR/maccfg
export CFGBIN=$CFGDIR/bin

# turn monitor mode OFF and suppress "[#] Done  /foo/bar" messages
set +o monitor

# no more annoying !
set +H

if [[ "$TERM" = "dumb" ]] ; then
  export TERM=xterm
fi

alias echoerr='>&2 echo'

BASHRC_D=$HOME/.bashrc.d
if [[ ! -e $BASHRC_D ]]; then
    echoerr Symlinking $CFGDIR/bashrc.d to $BASHRC_D...
    ln -fs $CFGDIR/bashrc.d $BASHRC_D
fi

export LOAD_COMPOSED_FUNCTIONS=0
BOOTSTRAP=$BASHRC_D/bootstrap
if ! source $BOOTSTRAP 2>/dev/null; then
    echoerr ERROR: Unable to find $BOOTSTRAP
    return
fi

# finally, load all my bash customizations
if [[ -e $BASHRC_D ]]; then
    SCRIPTS=$(find $BASHRC_D/enabled -name "*.sh" -print | sort)
    for SCRIPT in $SCRIPTS; do
        source_file $SCRIPT
    done
fi

restore_cursor_clear_line

if function_exists unshift_path; then
    # add dirs to the FRONT of the PATH
    unshift_path /usr/local/sbin
    unshift_path /usr/local/bin
    unshift_path /usr/local/opt/findutils/libexec/gnubin
    unshift_path $HOME/bin
else
    echoerr "Unable to add directories to front of path; unshift_path() not loaded"
fi

if function_exists uniq_path; then
    uniq_path # remove any duplicates in the PATH
else
    echoerr "Unable to remove duplicate directories from path; uniq_path() not loaded"
fi
