#!/usr/bin/env bash

p4vars () {
    set | grep ^P4
}

p4l () {
    PASSWORD=$(perl -e '
use Net::Netrc;
exit unless $ENV{P4PORT};
my ($host) = split /:/, $ENV{P4PORT};
my $entry = Net::Netrc->lookup($host);
print $entry->password;
')
    if [[ "$PASSWORD" != "" ]]; then
        echo "$PASSWORD" | p4 login >/dev/null
    else
        p4 login
    fi
    ~/BitBar/PerforceTicketStatus.1m.sh
}

p4_revertall () {
    p4 opened | perl -ne 's/\#.*$//; print;' | xargs p4 revert
}

is_git-p4_repo () {
    git rev-parse --symbolic --remotes 2>/dev/null | grep ^p4/
}
