#!/bin/bash
#
if is_local; then
    export EDITOR=xemacs
    alias xe=xemacs
else
    export EDITOR=emacs
    alias xe=emacs
fi

export GREP_COLOR='30;43'
export GREP_OPTIONS='--color=auto'
#alias grep='grep --color=auto'

alias clean='rm -fv *~ .*~'

alias clear='printf "\e[2J"'

alias word='open -a Microsoft\ Word.app'

alias bluehost='ssh dardanco@www.dardan.com'

alias eject="osascript -e 'tell application \"Finder\" to eject (every disk whose ejectable is true and local volume is true and free space is not equal to 0)'"

alias rsync_pwd_to='rsync -avz .'

# aliases specific to my workplace
