#!bash

export PACKYBIN=/tmp/packybin
source $PACKYBIN/setup_packybin.sh 2>/dev/null || \
    echo ERROR: Unable to find $PACKYBIN/setup_packybin.sh >> /dev/stderr

service () {
  /etc/init.d/$1 $2
}

rs () {
    for SERVICE in $@;
    do
        service $SERVICE restart;
    done
}
