#!/bin/bash

USER=$(whoami)
if [[ ! -w /usr/local ]]; then
    echo Error: The /usr/local directory is not writable.
    echo running sudo chown -R $USER:admin /usr/local
    sudo chown -R $USER:admin /usr/local
fi

if ! which brew >/dev/null 2>&1; then
    URL=https://raw.githubusercontent.com/Homebrew/install/master/install
    ruby -e "$(curl -fsSL $URL)"
fi
