#!/bin/bash

mkdir -p .d

#
# check to see if homebrew is installed
#
if ! which brew >/dev/null 2>&1; then
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

#
# make sure Caskroom is installed
#
if [[ ! -d $(brew --prefix)/Caskroom ]]; then
    brew tap homebrew/cask
    brew tap homebrew/cask-fonts
fi

#
# dependency files
#
if which brew >/dev/null 2>&1; then
    touch .d/homebrew
    brew list      | while read PKG; do touch .d/$PKG.brew; done
    brew --cask list | while read PKG; do touch .d/$PKG.cask; done
fi

