
/usr/local/bin/sshpass: /usr/local/Cellar/sshpass/1.06/bin/sshpass
	brew install https://raw.githubusercontent.com/kadwanev/bigboybrew/master/Library/Formula/sshpass.rb

/Applications/Keka.app:
	brew install Caskroom/cask/keka

/usr/local/bin/diff-so-fancy:
	brew install diff-so-fancy

/usr/local/bin/hr:
	brew install hr
