.PHONY: install
install: OpenHomeGoogleMail.app OpenWorkGoogleMail.app OpenGooglePlayMusic.app
	echo you need to install these by hand

%.app:
	#osacompile -x -o "$*.app" "$*.applescript"
	open /Applications/Utilities/Script\ Editor.app
